### ISSUE TITLE
gopkgs.com import no worky

### ISSUE THREAD

**Issue by kd5pbo** [tomerdmnt/geoipmap#5]
It seems gopkgs.com isn't up.  I get a 502 trying to import geoip.v1.

$ go get -v gopkgs.com/geoip.v1
Fetching https://gopkgs.com/geoip.v1?go-get=1
https fetch failed.
Fetching http://gopkgs.com/geoip.v1?go-get=1
Parsing meta tags from http://gopkgs.com/geoip.v1?go-get=1 (status code 502)
import "gopkgs.com/geoip.v1": parse http://gopkgs.com/geoip.v1?go-get=1: no go-import meta tags
package gopkgs.com/geoip.v1: unrecognized import path "gopkgs.com/geoip.v1"

**Comment by tomerdmnt** [comment]
Fixed it.
gopkgs.com is down, and rainycape/geoip does not allow import through github.com, so I vendored the package.

**Comment by kd5pbo** [comment]
Thanks :)
